export enum ActionType {
  FETCH_START = 'FETCH_START',
  FETCH_END = 'FETCH_END',
  SET_RESPONSE = 'SET_RESPONSE',
  SET_CURRENT_VILLAGE = 'SET_CURRENT_VILLAGE',
  SET_DISTRICT = 'SET_DISTRICT',
  SET_YEAR = 'SET_YEAR',
}
